// bce-ui/src/app/risk/risk.component.ts
import { Component, OnInit } from '@angular/core';
import {RiskTypeService} from '../services/risk-type.service';
import {Error} from 'tslint/lib/error';
import {HttpErrorResponse} from '@angular/common/http';
import {FormArray, FormControl, FormGroup, NgForm} from '@angular/forms';
import {AlertService} from '../services/alert.service';
import {Router} from '@angular/router';

@Component({
  selector: 'app-risk',
  templateUrl: './risk.component.html',
  styleUrls: ['./risk.component.scss']
})
export class RiskComponent implements OnInit {
  riskTypes: any;
  selectedRiskType: any;
  submitted = false;
  riskForm: FormGroup;

  constructor(private riskTypeService: RiskTypeService,
              private router: Router,
              private alertService: AlertService) {

  }

  ngOnInit() {
    this.riskTypeService.findAllRiskTypes().subscribe(data => {
        this.riskTypes = data;
        console.log('Here Be Data');
        console.log(data);
        // return data;
      },
      (err: HttpErrorResponse) => {
        if (err.error instanceof Error) {
          console.log('Client-side error occured.');
        } else {
          console.log('Server-side error occured.');
        }
      });
  }

  onChange(id) {
    // objArray.find(obj => obj.id == 3);
    this.selectedRiskType =  this.riskTypes.filter(x => x.id === parseInt(id))[0];
    console.log(id);
    console.log(this.selectedRiskType);
    // console.log(this.selectedRiskType.name);
    // this.selectedRiskType = newRiskType;

    this.riskForm = new FormGroup({});
    // this.riskForm = new FormArray({});

    for (let field of this.selectedRiskType.fields) {
      console.log(field.name);
      this.riskForm.addControl(field.name, new FormControl());
    }
  }

  onSubmit() {
    this.submitted = true;
    let bodyTemp = JSON.stringify(this.riskForm.value, function (key, value) {
      return value === null ? '' : value;
    });

    let body = {
      name: 'form data',
      data: btoa(bodyTemp)
    };

    this.riskTypeService.createRisk(body).subscribe(data => {

        this.alertService.success('Risk Created Successfully. ', true);
        this.router.navigate(['/']);
      },
      (err: HttpErrorResponse) => {
        if (err.error instanceof Error) {
          this.alertService.error('Client-side error occured.');
        } else {
          this.alertService.error('Server-side error occured.');
        }
      });
  }

}

<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
      <h2>Create Risk</h2>
      <label for="risk_type_dd">Please select risk type</label>
      <select class="form-control" id="risk_type_dd" required (change)="onChange($event.target.value)">
        <option value="" selected="true" disabled>Select Risk Type</option>
        <ng-container *ngFor="let i of riskTypes">
          <option [value]="i.id"  *ngIf="i.active">{{i.label}}</option>
        </ng-container>

      </select>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-sm-12" *ngIf="selectedRiskType">
    <form [formGroup]="riskForm" (ngSubmit)="onSubmit()">
      <h2>Creating new {{selectedRiskType.name}} risk</h2>
      <div class="form-group" *ngFor="let field of selectedRiskType.fields">
        <!--<label *ngIf="field.type == 'DROPDOWN'" for="{{field.name}}">{{field.label}}</label>-->
        <mat-form-field *ngIf="field.type == 'TEXT'">
          <input placeholder="{{field.label}}" matInput class="form-control"  required="{{field.required}}" name="{{field.name}}" formControlName="{{field.name}}"
                 [matTooltip]="field.tooltip" matTooltipPosition="right">
        </mat-form-field>

        <mat-form-field *ngIf="field.type == 'TEXTAREA'">
          <textarea placeholder="{{field.label}}" matInput class="form-control"  required="{{field.required}}" name="{{field.name}}" formControlName="{{field.name}}"
                    [matTooltip]="field.tooltip" matTooltipPosition="right"></textarea>
        </mat-form-field>

        <mat-form-field *ngIf="field.type == 'DATE'">
          <input matInput [matDatepicker]="picker" placeholder="{{field.label}}" class="form-control" required="{{field.required}}"
                 (click)="picker.open()" (focus)="picker.open()" name="{{field.name}}"  formControlName="{{field.name}}"
                 [matTooltip]="field.tooltip" matTooltipPosition="right">

          <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
          <mat-datepicker #picker></mat-datepicker>
        </mat-form-field>

        <mat-form-field class="example-full-width" *ngIf="field.type == 'CURRENCY'">
          <input placeholder="{{field.label}}" matInput type="number" required="{{field.required}}" name="{{field.name}}"  formControlName="{{field.name}}"
                 [matTooltip]="field.tooltip" matTooltipPosition="right">
        </mat-form-field>

        <mat-form-field class="example-full-width" *ngIf="field.type == 'EMAIL'">
          <input placeholder="{{field.label}}" matInput type="email" required="{{field.required}}" name="{{field.name}}"  formControlName="{{field.name}}"
                 [matTooltip]="field.tooltip" matTooltipPosition="right">
        </mat-form-field>

        <mat-form-field class="example-full-width" *ngIf="field.type == 'NUMBER'">
          <!--<input matInput placeholder="First name">-->
          <input placeholder="{{field.label}}" matInput type="number" required="{{field.required}}" name="{{field.name}}"  formControlName="{{field.name}}"
                 [matTooltip]="field.tooltip" matTooltipPosition="right">
        </mat-form-field>

        <mat-form-field class="example-full-width" *ngIf="field.type == 'INTEGER'">
          <input placeholder="{{field.label}}" matInput type="number" class="form-control integer"  required="{{field.required}}" name="{{field.name}}"  formControlName="{{field.name}}"
                 [matTooltip]="field.tooltip" matTooltipPosition="right">
        </mat-form-field>

        <mat-form-field *ngIf="field.type == 'FLOAT'">
          <input placeholder="{{field.label}}" matInput class="form-control real_number"  required="{{field.required}}" name="{{field.name}}"  formControlName="{{field.name}}"
                 [matTooltip]="field.tooltip" matTooltipPosition="right">
        </mat-form-field>
        <mat-radio-group class="radio-group" *ngIf="field.type == 'RADIO'" formControlName="{{field.name}}">
          <label>{{field.label}}</label>
          <!--<label class="form-control" *ngFor="let option of field.options" >  -->
            <mat-radio-button  class="radio-button"  *ngFor="let option of field.options" name="{{field.name}}"  [value]="option.choice"
                               [matTooltip]="field.tooltip" matTooltipPosition="right">
              {{option.label}}
            </mat-radio-button>

          <!--</label>-->
        </mat-radio-group>
        <mat-form-field *ngIf="field.type == 'DROPDOWN'">
          <mat-select placeholder="{{field.label}}" required="{{field.required}}"  formControlName="{{field.name}}"
                      [matTooltip]="field.tooltip" matTooltipPosition="right">
            <mat-option value="" selected="true" disabled>Select {{field.name}}</mat-option>
            <mat-option  *ngFor="let option of field.options" [value]="option.choice">{{option.label}}</mat-option>
          </mat-select>
        </mat-form-field>

      </div>
      <button type="submit" class="btn btn-success">Submit</button>
    </form>
  </div>
</div>

// bce-vue-ui/src/components/Risk.vue
<template>
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <h2>Create Risk</h2>
                    <label for="risk_type_dd">Please select risk type</label>
                    <select class="form-control" id="risk_type_dd" required v-model="selected">
                        <option value="" selected="true" disabled>Select Risk Type</option>
                        <option v-for="(riskType, index) in riskTypes" v-bind:key="index" v-bind:value="riskType">
                            {{riskType.label}}
                        </option>
                    </select>
                </div>
            </div>
        </div>

        <div class="row" v-if="selected && selected.name">
            <div class="col-sm-12">
                <form @submit.prevent="submit">
                    <h2>Creating new {{selected.name}} risk</h2>
                    <div v-for="(field, index) in selected.fields" v-bind:key="index">
                        <md-field v-if="field.type == 'TEXT'">
                            <label>{{field.label}}</label>
                            <md-input v-model="models[field.name]"
                                      :required="field.required"
                                      :name="field.name">
                                <md-tooltip md-direction="right">{{field.tooltip}}</md-tooltip>
                            </md-input>
                        </md-field>

                        <md-field v-if="field.type == 'TEXTAREA'">
                            <label>{{field.label}}</label>
                            <md-textarea v-model="models[field.name]" :name="field.name" :required="field.required">
                                <md-tooltip md-direction="right">{{field.tooltip}}</md-tooltip>
                            </md-textarea>
                        </md-field>

                        <md-datepicker v-model="models[field.name]" v-if="field.type == 'DATE'" :name="field.name"
                                       :required="field.required">
                            <label>{{field.label}}</label>
                            <md-tooltip md-direction="right">{{field.tooltip}}</md-tooltip>
                        </md-datepicker>

                        <md-field v-if="field.type == 'EMAIL'">
                            <label>{{field.label}}</label>
                            <md-input type="email" v-model="models[field.name]"
                                      :required="field.required"
                                      :name="field.name">
                                <md-tooltip md-direction="right">{{field.tooltip}}</md-tooltip>
                            </md-input>
                        </md-field>

                        <md-field
                                v-if="field.type == 'NUMBER' || field.type == 'INTEGER' || field.type == 'FLOAT' || field.type == 'CURRENCY'">
                            <label>{{field.label}}</label>
                            <span v-if="field.type == 'CURRENCY'" class="md-prefix">$</span>
                            <md-input v-model="models[field.name]" type="number" :required="field.required"
                                      :name="field.name">
                                <md-tooltip md-direction="right">{{field.tooltip}}</md-tooltip>
                            </md-input>
                        </md-field>


                        <div v-if="field.type == 'RADIO'">
                            <label>{{field.label}}</label>
                            <br/>
                            <md-radio v-model="models[field.name]" v-for="(option, index) in field.options"
                                      :id="field.name" :name="field.name" v-bind:key="index" :value="option.choice">
                                {{option.label}}
                            </md-radio>
                        </div>

                        <md-field v-if="field.type == 'DROPDOWN'">
                            <label>{{field.label}}</label>
                            <md-select v-model="models[field.name]" :id="field.name" :name="field.name">
                                <md-option v-for="(option, index) in field.options"
                                           v-bind:key="index" :value="option.choice">{{option.label}}
                                </md-option>
                            </md-select>
                        </md-field>
                    </div>
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </div>
        </div>
    </div>
</template>

<script>
    import riskTypeService from '@/services/risktype.service';

    export default {
        name: "Risk",
        data() {
            return {
                riskTypes: [{},{}],
                selected: null,
                models: {},
            };

        },
        created: function () {
            this.getAll();
        },
        methods: {
            getAll() {
                riskTypeService.getAll().then(riskTypes => {
                    this.riskTypes = riskTypes;
                })
            },
            submit() {
                let model = {};

                model['name'] = this.selected.name;

                model['data'] = btoa(JSON.stringify(this.models));

                riskTypeService.createRisk(model).then(response => {
                    response.text().then(text => {
                        this.res = JSON.parse(text);

                        // redirect to home
                        if (response.status == 200 || response.status == 201) {
                            this.$router.push({
                                path: '/',
                            });

                            this.$store.dispatch('alert/success', "A new " + this.res.name + " Risk has been created with reference number: " + this.res.id);
                        } else if (response.status == 400) {

                            for (var msg in this.res) {
                                this.$store.dispatch('alert/error', msg + ": " + this.res[msg]);
                            }
                        }
                    });
                }).catch(err => {
                    // console.log(err);
                });
            }
        },

    }
</script>

<style scoped>
    /*.md-datepicker-dialog {*/
    /*height: 286px;*/
    /*}*/
    /*.md-datepicker-body-content {*/
    /*height: 232px !important;*/
    /*}*/
</style>
