// ui/src/components/RiskType.vue
<template>
  <div class="row">
    <div class="col-md-12">
      <h2>Create Risk Type</h2>
    </div>
    <div class="col-md-12">
      <form @submit.prevent="submit">
        <div class="form-group">
          <label>Name</label>
          <input
            class="form-control"
            required
            name="name"
            v-model="model['name']"
          />
        </div>
        <div class="form-group">
          <label>Label</label>
          <input
            class="form-control"
            required
            name="label"
            v-model="model['label']"
          />
        </div>
        <div class="form-group">
          <label>Description</label>
          <textarea
            class="form-control"
            name="description"
            v-model="model['description']"
          ></textarea>
        </div>
        <div class="form-group">
          <label>Tool Tips</label>
          <input
            class="form-control"
            name="tooltip"
            v-model="model['tooltip']"
          />
        </div>
        <div class="form-group">
          <label class="form-control" for="active">
            <input
              name="active"
              id="active"
              v-model="model['active']"
              type="checkbox"
            />
            Active
          </label>
        </div>

        <!--<section formArrayName="fields">-->
        <h3>Field</h3>
        <div class="row">
          <div
            class="alert alert-success col-sm-6"
            v-for="(field, index) in model['fields']"
            v-bind:key="index"
          >
            <!--<div formGroupName="{{i}}">-->
            <div class="form-group">
              <label>Name</label>
              <input
                class="form-control"
                required
                name="name"
                v-model="field.name"
              />
            </div>
            <div class="form-group">
              <label>Label</label>
              <input
                class="form-control"
                required
                name="label"
                v-model="field.label"
              />
            </div>
            <div class="form-group">
              <label>Tool Tips</label>
              <input
                class="form-control"
                name="tooltip"
                v-model="field.tooltip"
              />
            </div>
            <div class="form-group">
              <label for="type">Field Type</label>
              <select
                class="form-control"
                name="type"
                id="type"
                v-model="field.type"
                v-on:change="changeType(field, index)"
              >
                <option value="TEXT">Text Field</option>
                <option value="TEXTAREA">Text Area</option>
                <option value="EMAIL">Email Address</option>
                <option value="DATE">Date</option>
                <option value="CURRENCY">Currency</option>
                <option value="NUMBER">Number</option>
                <option value="RADIO">Radio Buttons</option>
                <option value="DROPDOWN">Dropdown</option>
              </select>
            </div>
            <div v-if="field.options.length > 0">
              <table class="table">
                <tr>
                  <th><label>Choice</label></th>
                  <th><label>Label</label></th>
                  <th></th>
                </tr>
                <tr v-for="(option, i) in field.options" v-bind:key="i">
                  <!--<ng-container formGroupName="{{j}}">-->
                  <td>
                    <input
                      class="form-control"
                      name="choice"
                      v-model="option.choice"
                    />
                  </td>
                  <td>
                    <input
                      class="form-control"
                      name="label"
                      v-model="option.label"
                    />
                  </td>
                  <td>
                    <button
                      class="btn btn-default"
                      type="button"
                      title="Remove Option"
                      v-on:click="removeOption(field, i)"
                    >
                      Remove Option
                    </button>
                  </td>
                </tr>
                <tr>
                  <td>
                    <button
                      class="btn btn-primary"
                      type="button"
                      title="Add Option"
                      v-on:click="addOption(field)"
                    >
                      Add Option
                    </button>
                  </td>
                </tr>
              </table>
            </div>
            <div class="form-group">
              <label class="form-control">
                <input
                  v-model="field.required"
                  type="checkbox"
                  checked="false"
                />
                Required
              </label>
            </div>
            <!--</div>-->
            <button
              class="btn btn-default"
              type="button"
              title="Remove Field"
              v-on:click="removeField(index)"
            >
              Remove Field
            </button>
          </div>
        </div>
        <button
          class="btn btn-primary"
          type="button"
          title="Add Field"
          v-on:click="addField()"
        >
          Add Field
        </button>
        <!--</section>-->

        <div>
          <hr />
          <button class="btn btn-primary" type="button" v-on:click="submit()">
            Save
          </button>
        </div>
      </form>
    </div>
    <hr />
  </div>
</template>

<script>
import riskTypeService from "@/services/risktype.service";
import { mapActions } from "vuex";

export default {
  name: "RiskType",
  data() {
    return {
      riskType: null,
      model: {
        active: true,
        fields: []
      }
    };
  },
  created: function() {
    this.addField();
  },
  methods: {
    ...mapActions(["success", "error", "clear"]),
    removeField(index) {
      this.model["fields"].splice(index, 1);
    },
    addField() {
      this.model["fields"].push({
        name: "",
        label: "",
        type: "TEXT",
        tooltip: "",
        options: [],
        required: false
      });
    },
    addOption(field) {
      field.options.push({
        choice: "",
        label: ""
      });
    },
    removeOption(field, index) {
      field.options.splice(index, 1);
    },
    changeType(field) {
      if (field.type == "RADIO" || field.type == "DROPDOWN") {
        this.addOption(field);
      } else {
        field.options = [];
      }
    },
    submit() {
      riskTypeService
        .createRiskType(this.model)
        .then(response => {
          response.text().then(text => {
            this.res = JSON.parse(text);
            // redirect to home
            if (response.status == 200 || response.status == 201) {
              this.$store.dispatch(
                "alert/success",
                "A new Risk Type has been created with reference number: " +
                  this.res.id
              );
              this.$router.push({
                path: "/"
              });
            } else if (response.status == 400) {
              for (var msg in this.res) {
                this.$store.dispatch("alert/error", msg + ": " + this.res[msg]);
              }
            }
          });
        })
        .catch(err => {});
    }
  }
};
</script>

<style scoped></style>

// bce-ui/src/app/risk-type/risk-type.component.ts
import { Component, OnInit } from '@angular/core';
import {FormArray, FormControl, FormGroup} from '@angular/forms';
import {RiskTypeService} from '../services/risk-type.service';
import {Error} from 'tslint/lib/error';
import {HttpErrorResponse} from '@angular/common/http';
import {Router} from '@angular/router';
import {AlertService} from '../services/alert.service';

@Component({
  selector: 'app-risk-type',
  templateUrl: './risk-type.component.html',
  styleUrls: ['./risk-type.component.scss']
})
export class RiskTypeComponent implements OnInit {
  riskTypeForm: FormGroup;
  submitted = false;
  index = 0;
  active = true;

  constructor(
    private riskTypeService: RiskTypeService,
    private router: Router,
    private alertService: AlertService
  ) { }

  ngOnInit() {
    this.riskTypeForm = new FormGroup({});

    this.riskTypeForm.addControl('name', new FormControl());
    this.riskTypeForm.addControl('label', new FormControl());
    this.riskTypeForm.addControl('description', new FormControl());
    this.riskTypeForm.addControl('tooltip', new FormControl());
    this.riskTypeForm.addControl('active', new FormControl());
    // this.riskTypeForm.addControl('fields', new FormArray([]));
    this.riskTypeForm.addControl('fields', new FormArray([this.createNewField()]));
    // this.optionsNeeded[0] = true;
    // this.optionsNeeded.push(false);
  }

  createNewField() {
    let field = new FormGroup({});

    field.addControl('name', new FormControl());
    field.addControl('label', new FormControl());
    field.addControl('tooltip', new FormControl());
    field.addControl('type', new FormControl());
    field.addControl('visible', new FormControl());
    field.addControl('hidden', new FormControl());
    field.addControl('required', new FormControl());
    field.addControl('options', new FormArray([]));
    this.index++;
    return field;
  }

  createNewOption() {
    let option = new FormGroup({});
    option.addControl('choice', new FormControl());
    option.addControl('label', new FormControl());
    return option;
  }
  onAddField() {
    (this.riskTypeForm.controls['fields'] as FormArray).push(this.createNewField());
  }
  onRemoveField(optionIndex) {
    (this.riskTypeForm.controls['fields'] as FormArray).removeAt(optionIndex);
  }

  onAddOption(fieldGroup: FormGroup) {
    (fieldGroup.controls.options as FormArray).push(this.createNewOption());
  }
  onRemoveOption(fieldGroup: FormGroup, j) {
    (fieldGroup.controls.options as FormArray).removeAt(j);
  }

  onChange(fieldGroup: FormGroup, value) {
    // objArray.find(obj => obj.id == 3);
    if (value === 'RADIO' || value === 'DROPDOWN') {
      (fieldGroup.controls.options as FormArray).push(this.createNewOption());
    } else {
      while ((fieldGroup.controls.options as FormArray).length) {
        (fieldGroup.controls.options as FormArray).removeAt(0);
      }
    }
  }

  onSubmit() {
    this.submitted = true;
    console.log('Submitted');
    console.log(this.riskTypeForm);
    console.log(this.riskTypeForm.value);
    console.log(JSON.stringify(this.riskTypeForm.value));
    let body; // = this.riskTypeForm.value; // JSON.stringify(this.riskTypeForm.value);

    let bodyTemp = JSON.stringify(this.riskTypeForm.value, function (key, value) {
        return value === null ? '' : value;
    });
    bodyTemp = bodyTemp.split('"active":""').join('"active":false');
    bodyTemp = bodyTemp.split('"visible":""').join('"visible":false');
    bodyTemp = bodyTemp.split('"hidden":""').join('"hidden":false');
    bodyTemp = bodyTemp.split('"required":""').join('"required":false');

    body = JSON.parse(bodyTemp);


    this.riskTypeService.createRiskTypes(body).subscribe(data => {

        this.alertService.success('Risk Type Created', true);
        this.router.navigate(['/']);
      },
      (err: HttpErrorResponse) => {
        if (err.error instanceof Error) {
          this.alertService.error('Client-side error occured.');
        } else {
          this.alertService.error('Server-side error occured.');
        }
      });
  }
}

<div class="row">
  <div class="col-md-12">
    <h2>Create Risk Type</h2>
  </div>
  <div class="col-md-12">
    <form [formGroup]="riskTypeForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control" required name="name" id="name" formControlName="name" >
      </div>
      <div class="form-group">
        <label for="label">Label</label>
        <input class="form-control" required name="label" id="label" formControlName="label" >
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" name="description" formControlName="description" ></textarea>
      </div>
      <div class="form-group">
        <label for="tooltip">Tool Tips</label>
        <input class="form-control" name="tooltip" id="tooltip" formControlName="tooltip" >
      </div>
      <div class="form-group">
        <label class="form-control" for="active">
          <input name="active" id="active" formControlName="active" [(ngModel)]="active" type="checkbox" >
          Active
        </label>
      </div>

      <section formArrayName="fields">
        <h3>Field</h3>
        <div class="row">
          <div class="alert alert-success col-md-3 col-sm-6" *ngFor="let field of riskTypeForm.controls.fields.controls; index as i">
            <div formGroupName="{{i}}">
              <div class="form-group">
                <label for="name">Name</label>
                <input class="form-control" required id="name" name="name" formControlName="name" >
              </div>
              <div class="form-group">
                <label for="label">Label</label>
                <input class="form-control" required name="label" id="label" formControlName="label" >
              </div>
              <div class="form-group">
                <label for="tooltip">Tool Tips</label>
                <input class="form-control" name="tooltip" id="tooltip" formControlName="tooltip" >
              </div>
              <div class="form-group">
                <label for="type">Field Type</label>
                <select class="form-control" name="type" id="type" formControlName="type" (change)="onChange(field, $event.target.value)">
                  <option value="TEXT">Text Field</option>
                  <option value="TEXTAREA">Text Area</option>
                  <option value="EMAIL">Email Address</option>
                  <option value="DATE">Date</option>
                  <option value="CURRENCY">Currency</option>
                  <option value="NUMBER">Number</option>
                  <!--<option value="INTEGER">Natural Number</option>-->
                  <!--<option value="FLOAT">Real Number</option>-->
                  <option value="RADIO">Radio Buttons</option>
                  <option value="DROPDOWN">Dropdown</option>
                </select>
              </div>
              <div *ngIf="field.controls.options.controls.length > 0" formArrayName="options">
                <table class="table">
                  <tr *ngFor="let option of field.controls.options.controls; index as j">
                    <div formGroupName="{{j}}">
                      <td><label for="choice">Choice</label></td>
                      <td>
                        <input class="form-control" name="choice" id="choice" formControlName="choice" >
                      </td>
                      <td><label for="label">Label</label></td>
                      <td>
                        <input class="form-control" name="label" id="label" formControlName="label" >
                      </td>
                      <td><button class="btn btn-default" type="button" title="Remove Option" (click)="onRemoveOption(field, j)">Remove Option</button></td>
                    </div>
                  </tr>
                  <tr>
                    <td><button class="btn btn-primary" type="button" title="Add Option" (click)="onAddOption(field)">Add Option</button></td>
                  </tr>
                </table>
              </div>
              <!--<div class="form-group">-->
              <!--<label class="form-control" for="visible">-->
              <!--<input required name="visible" id="visible" formControlName="visible" type="checkbox"-->
              <!--ng-true-value="true" ng-false-value="false" checked>-->
              <!--Visible-->
              <!--</label>-->
              <!--</div>-->
              <!--<div class="form-group">-->
              <!--<label class="form-control" for="hidden">-->
              <!--<input required name="hidden" id="hidden" formControlName="hidden" type="checkbox" checked="false">-->
              <!--Hidden-->
              <!--</label>-->
              <!--</div>-->
              <div class="form-group">
                <label class="form-control" for="required">
                  <input required name="required" id="required" formControlName="required" type="checkbox" checked="false">
                  Required
                </label>
              </div>
            </div>
            <button class="btn btn-default" type="button" title="Remove Field" (click)="onRemoveField(i)">Remove Field</button>
          </div>
        </div>

        <button class="btn btn-primary" type="button" title="Add Field" (click)="onAddField()">Add Field</button>
      </section>
      <button class="btn btn-primary" type="button"  (click)="onSubmit()">Save</button>
    </form>
  </div>
</div>
